import pandas as pd
import random
from tabulate import tabulate


def pandas_series():

    # Generating the dict for the series load of the data

    data = {i : random.randint(10,100) for i in range(20)}

    print("###################**********###################********############")
    print(f"The dictionary being used to create the pandas series is generated by random number\n--> Below is the generated data\n{data}")
    print("###################**********###################********############")

    # Creating the series for the pandas

    pd_series = pd.Series(data)
    pd_series.name = 'Values'

    print(f"Below is the created pandas series :\n{pd_series}")

    print("Using pandas function to see the series distribution\n1. Mean\n2. Max\n3. Min")

    print(pd_series.describe())

def pandas_dataframe():

    # Generating the dict for the dataframe load of the data

    data = [
        ["Frog",1,"Bugs","Amphibian",4],
        ["Dog", 2,"Pedigree","Mammal",4],
        ["Wood Pecker", 1,"Worms","Bird",2],
        ["Dragon", 100, "all life forms","Mythical Reptile",2],
        ["Pikachu", 3, "Poke Chips", "Rodent Omnivore", 4]
    ]

    column_names = ["Recognizer","Age","Food source","Life Form", "Leg Count"]

    pd_df = pd.DataFrame(data,columns=column_names)

    print("###################**********###################********############")
    print(f"The lists are being used to create the pandas data frames\n--> Below are the lists\n1. Data list : ")
    for i in data:
        print(i)
    print(f"The columns used are : {column_names}")
    print("###################**********###################********############")
    print("Below is the created data frame")
    print(tabulate(pd_df, headers='keys', tablefmt='psql',showindex=False))
    print("\nAccessing the columns of the data frame")

    for col_name, col_data in pd_df.items():
        print(f"Column name : {col_name}")
        print(col_data)
        print()



if __name__ == '__main__':
    pandas_series()
    pandas_dataframe()